pub mod load_8bit_instructions;
pub mod load_16bit_instructions;
pub mod opcodes_utils;
pub mod arithmetic_8bit_instructions;
pub mod arithmetic_16bit_instructions;
pub mod jump_instructions; 
pub mod cpu_control_instructions;
pub mod rotate_shift_instructions;
pub mod single_bit_sintructions;