[workspace]
resolver = "2"

members = [
    "sdl",
    "core",
    "rpi",
    "common", 
    "libretro",
    "nx"
]

[workspace.package]
version = "4.2.0"
authors = ["alloncm <alloncm@gmail.com>"]
rust-version = "1.74"   # cause of cbindgen used to build for nx
edition = "2021"

[profile.release]
lto = true  # Samller binaries and faster code

# Without this profile getting stackoverflow on debug builds
[profile.dev]
codegen-units = 1
opt-level = 2
debug = true
