[workspace]
members = [
    "sdl",
    "core",
    "rpi",
    "common"
]

[workspace.package]
version = "3.0.2"
authors = ["alloncm <alloncm@gmail.com>"]
rust-version = "1.65"   # cause of let else feature