#ifndef MAGENBOY_H
#define MAGENBOY_H

// Do not edit this file directly, it is autogenerated by cbindgen during build process

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum EmulatorMenuOption {
  Resume = 0,
  Restart = 1,
  Shutdown = 2,
  Turbo = 3,
};
typedef uint32_t EmulatorMenuOption;

typedef void (*LogCallback)(const char*, int len);

typedef void (*GfxDeviceCallback)(const uint16_t *buffer);

typedef uint64_t (*JoypadProviderCallback)(void);

typedef uint64_t (*PollJoypadProviderCallback)(void);

typedef int16_t Sample;

typedef void (*AudioDeviceCallback)(const Sample *buffer, int size);

void magenboy_init_logger(LogCallback log_cb);

/**
 * SAFETY: rom size must be the size of rom
 */
void *magenboy_init(const char *rom,
                    unsigned long long rom_size,
                    GfxDeviceCallback gfx_cb,
                    JoypadProviderCallback joypad_cb,
                    PollJoypadProviderCallback poll_joypad_cb,
                    AudioDeviceCallback audio_cb);

void magenboy_deinit(void *ctx);

const char *magenboy_menu_trigger(GfxDeviceCallback gfx_cb,
                                  JoypadProviderCallback joypad_cb,
                                  PollJoypadProviderCallback poll_joypad_cb,
                                  const char *const *roms,
                                  uint32_t roms_count);

EmulatorMenuOption magenboy_pause_trigger(GfxDeviceCallback gfx_cb,
                                          JoypadProviderCallback joypad_cb,
                                          PollJoypadProviderCallback poll_joypad_cb);

/**
 * SAFETY: ctx is a valid pointer to a GameBoy instance
 */
void magenboy_cycle_frame(void *ctx);

void magenboy_get_dimensions(uint32_t *width, uint32_t *height);

void magenboy_get_sram(void *ctx, uint8_t **ptr, uintptr_t *size);

extern void *malloc(uintptr_t size);

extern void free(void *ptr);

#endif  /* MAGENBOY_H */
