use magenboy_common::VERSION;

// Export values for the C application to use
fn main() {
    let authors = env!("CARGO_PKG_AUTHORS");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut out_vars_path = std::path::Path::new(&out_dir).to_path_buf();
    out_vars_path.pop();
    out_vars_path.pop();
    out_vars_path.pop();
    std::fs::write(out_vars_path.join("version.txt"), VERSION).expect("Unable to write version file");
    std::fs::write(out_vars_path.join("authors.txt"), authors).expect("Unable to write authors file");

    // Generate C bindings
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::Builder::new()
      .with_crate(crate_dir)
      .with_parse_deps(true)
      .with_parse_include(&["magenboy_core", "magenboy_common"])
      .with_include_guard("MAGENBOY_H")
      .with_language(cbindgen::Language::C)
      .with_autogen_warning("// Do not edit this file directly, it is autogenerated by cbindgen during build process")
      .generate()
      .expect("Unable to generate bindings")
      .write_to_file("src/magenboy.h");
}