name: Rust

on:
  push:
    branches: [ master, feature/all_targets_ci ]
  pull_request:
    branches: [ master, feature/*, fix/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-all-targets:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:  
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.73.0
        rustflags: ""
        cache-directories: "/home/runner/.cargo/bin
          C:\\Users\\runneradmin\\.cargo\\bin"
    - name: install cargo make
      run: cargo install --no-default-features --locked --version 0.37.23 cargo-make
    - name: Run tests
      run: cargo make test
    # for some reason the sdl installation causing this to fail (some error about not finding glibc) so this should before the sdl
    - name: rpi os
      if: ${{ matrix.os == 'ubuntu-latest' }}  # This fails on windows since it does not have docker installed
      run: cargo make rpios
    - name: Build sdl
      run: cargo make sdl
    - name: Build libretro
      run: cargo make libretro_desktop
    - name: rpi baremetal
      run: |
       rustup toolchain install nightly
       cargo make -e RPI=4 rpibm