name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/*, fix/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build sdl
      run: cargo build --verbose --package magenboy_sdl
    - name: Run tests
      run: cargo test --verbose --package magenboy_core
