name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feature/*, fix/* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-all-targets:
    strategy: 
      fail-fast: false  # Allow the other job to continue running
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:  
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.73.0, nightly-2023-10-05
        target: aarch64-linux-android
        rustflags: ""
        cache-directories: "/home/runner/.cargo/bin
          C:\\Users\\runneradmin\\.cargo\\bin"

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r25  # This is the minimum version rust supports
        add-to-path: false

    - name: install cargo make
      run: cargo install --no-default-features --locked --version 0.37.23 cargo-make
      
    - name: Build libretro android
      run: cargo make libretro_android
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: Run tests
      run: cargo make test

    # for some reason the sdl installation causing this to fail (some error about not finding glibc) so this should before the sdl
    - name: Build rpi os
      if: ${{ matrix.os == 'ubuntu-latest' }}  # This fails on windows since it does not have docker installed
      run: cargo make rpios
      
    - name: Build rpi baremetal
      run: cargo make -e RPI=4 rpibm

    - name: Build sdl
      run: cargo make sdl

    - name: Build sdl with debugger
      run: cargo make sdl_dbg

    - name: Build libretro desktop
      run: cargo make libretro_desktop